# Generated by Django 2.2.6 on 2023-01-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_whitelistedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedIpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='User name')),
                ('ip', models.CharField(max_length=300, verbose_name='IP Address')),
                ('validation_msg', models.CharField(max_length=1000, verbose_name='Validation message')),
                ('ip_restriction', models.BooleanField(default=True, verbose_name='Ip restriction')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
